browserConfig:
  browserEnum: CHROME
#FIREFOX
#EDGE
#IE

browserProperties:
  webElementTimeOut: 20
  webBrowserImplicitTimeOut: 22


environment:
  intEnv:
    appUrl: http://146.59.32.4/
    env_name: intEnv
    firstName: Albert
    lastName: Einstein
    email: ae@example.com
    password: ae123456
    titleOnSalePage: ON SALE
    discountSize: 20.00
    productNameWithBlockedCartButton: CUSTOMIZABLE MUG
    customizationMessage: qwerty
    shippingCost: 7.0
    Address: Poloneza street, 50
    City: Warsaw
    Country: Poland
    PostalCode: 05-500
    DeliveryOptionName: My carrier
    PaymentStatus: Awaiting bank wire payment
    SynonymicNameBankWirePaymentMethod: Bank transfer
    expectedMessage: Form send with success
    pathToFileForUpload: src/main/resources/fileForUpload.txt
    active: true

  testEnv:
    appUrl: http://146.59.32.4/
    env_name: testEnv
    firstName: Leonardo
    lastName: DaVinci
    email: ld@example.com
    password: ld123456
    titleOnSalePage: ON SALE
    discountSize: 20.00
    productNameWithBlockedCartButton: CUSTOMIZABLE MUG
    customizationMessage: qwerty
    shippingCost: 7.0
    Address: Poloneza street, 50
    City: Warsaw
    Country: Poland
    PostalCode: 05-500
    DeliveryOptionName: My carrier
    PaymentStatus: Awaiting bank wire payment
    SynonymicNameBankWirePaymentMethod: Bank transfer
    expectedMessage: Form send with success
    pathToFileForUpload: src/main/resources/fileForUpload.txt
    active: false

  defaultEnv:
    appUrl: http://146.59.32.4/
    env_name: defaultEnv
    firstName: Jack
    lastName: Jackson
    email: JJ@example.com
    password: jj123456
    titleOnSalePage: ON SALE
    discountSize: 20.00
    productNameWithBlockedCartButton: CUSTOMIZABLE MUG
    customizationMessage: qwerty
    shippingCost: 7.0
    Address: Poloneza street, 50
    City: Warsaw
    Country: Poland
    PostalCode: 05-500
    DeliveryOptionName: My carrier
    PaymentStatus: Awaiting bank wire payment
    SynonymicNameBankWirePaymentMethod: Bank transfer
    expectedMessage: Form send with success
    pathToFileForUpload: src/main/resources/fileForUpload.txt
    active: false